name: Build and Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 8
    - name: Build with Maven
      env:
        CLIENT_ID: ${{ secrets.anypoint_client_id }}
        CLIENT_SECRET: ${{ secrets.anypoint_client_secret }}
        nexus_username: ${{ secrets.nexus_username }}
        nexus_password: ${{ secrets.nexus_password }}
        ORGANIZATION_ID: "37c5b454-1998-4efa-a633-cd45c824f500"
      run: mvn deploy --file pom.xml --settings .maven/settings.xml -DskipMunitTests
